[project]
name = "testing-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "s-shivanand", email = "sharana.shivanand@gmail.com" }
]
requires-python = ">=3.14.4"
dependencies = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "sphinx>=9.1.0",
    "sphinx-autodoc-typehints>=3.13.6",
    "sphinx-rtd-theme>=3.1.0",
]

[project.scripts]
testing-calculator = "testing_calculator:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
